### ISSUE TITLE
AssertionError: _dist_info should not exist when repo is in place

### ISSUE THREAD

**Issue by zhengyuntao123** [SamsungLabs/zero-cost-nas#10]
When I run python nasbench2_pred.py as mentioned in the reproducing results part, I encounter with such error: 
Traceback (most recent call last):
  File "/home/yuntao/test/zero-cost-nas/nasbench2_pred.py", line 20, in <module>
    from foresight.models import *
  File "/home/yuntao/test/zero-cost-nas/foresight/__init__.py", line 16, in <module>
    from .version import *
  File "/home/yuntao/test/zero-cost-nas/foresight/version.py", line 44, in <module>
    assert not has_repo, '_dist_info should not exist when repo is in place'
AssertionError: _dist_info should not exist when repo is in place

**Comment by vaenyr** [comment]
How did you install the package? This can sometimes happen if you first install without, and then with, the `-e` option.
To make sure everything is as expected, I would recommend uninstalling the package first (run it as many times as needed until you see a message saying there's no package to uninstall), then remove the `_dist_info.py` file from the cloned repo, install again with the `-e` (if that's what you want).

Let me know if that helped.

**Comment by zhengyuntao123** [comment]
Thank you for your quick reply.
I didn't try `pip install -e .`. However, I find that whenever I remove the whole directory, git clone it again and `pip install .`, it runs properly at first time. But if I run `pip install .` again, errors would arise:
Processing /home/yuntao/zero-cost-nas
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [14 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/home/yuntao/zero-cost-nas/setup.py", line 31, in <module>
          spec.loader.exec_module(package_version)
        File "<frozen importlib._bootstrap_external>", line 850, in exec_module
        File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
        File "/home/yuntao/zero-cost-nas/foresight/version.py", line 43, in <module>
          from . import _dist_info as info
        File "/home/yuntao/zero-cost-nas/foresight/__init__.py", line 16, in <module>
          from .version import *
        File "/home/yuntao/zero-cost-nas/foresight/version.py", line 44, in <module>
          assert not has_repo, '_dist_info should not exist when repo is in place'
      AssertionError: _dist_info should not exist when repo is in place
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by zhengyuntao123** [comment]
Thanks a lot.

After deleting `_dist_info.py`, I could properly run `python nasbench2_pred.py`.

By the way, my pip version is `22.1.2`. Maybe the problem is due to the `pip` version.
